### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by edi9999**
Can you please publish a new version to npm after merging this PR ?

### CODE REVIEW

**Comment by fb55** [comment]
Could you elaborate on why this is needed?

**Comment by edi9999** [comment]
The current released project is not being recognized automatically by https://github.com/iandotkelly/nlf , a tool to find out which licenses your dependencies have. 

This commit fixes this.

I also personally think that it is good for projects to be explicit about the license they use, it is faster to  see : this is "BSD License" than to read the license text, and compare it withlicense texts found on google.

**Comment by jugglinmike** [comment]
Shouldn't the tool reference the `license` attribute in the project's `package.json` file? Inferring the name through analysis of a text blob seems kind of brittle.

**Comment by fb55** [comment]
I agree with Mike, the package.json should suffice.

**Pull request closed without merging**
